### PR TITLE
feat: stream support target database

### PR DESCRIPTION
**Pull request by zhaoyanggh**

### CODE REVIEW

**Review by sangshuduo — CHANGES_REQUESTED** [review]
concern on never check if the pointer is null

**Comment by zhaoyanggh** [comment]
> concern on never check if the pointer is null

I initialize the bench array like streams, and if there is no stream in streams bench arry, then streams->size will be 0 and will never run into the for loop

**Review by sangshuduo — APPROVED** [review]
LGTM

**Review by afwerar — APPROVED** [review]
LGTM

**Pull request merged**
