### PR TITLE
fix: deal dot in table name

### PR DESCRIPTION
**Pull request by DuanKuanJun**

### CODE REVIEW

**Review by sangshuduo — COMMENTED** [review]
From a product viewpoint, I would suggest adding a command line parameter to let the user explicitly chooses the replacing-dot behavior to avoid incompatible issue

**Comment by sangshuduo** [comment]
https://github.com/taosdata/taos-tools/issues/689

**Comment by DuanKuanJun** [comment]
> From a product viewpoint, I would suggest adding a command line parameter to let the user explicitly chooses the replacing-dot behavior to avoid incompatible issue

I agree, need a option to open replacing-dot behavior, default is close this option.

**Review by sangshuduo — APPROVED** [review]
LGTM

**Pull request merged**
