### PR TITLE
fix/windows-getTimeOfDay

### PR DESCRIPTION
**Pull request by facetosea**

### CODE REVIEW

**Review by sangshuduo — COMMENTED** [review]
Seems TDengine 3.0/main still use same logic of implementation. interested why taos-tools need to change.

**Comment by facetosea** [comment]
> Seems TDengine 3.0/main still use same logic of implementation. interested why taos-tools need to change.

In such a scenario, an error will occur. At the moment of x seconds and 999 milliseconds, the value of the variable ”t“ is obtained through toolsGetTimestampSec, and the value of the variable ”st” is obtained through the GetLocalTime function at the moment of x + 1 seconds and 0 milliseconds;

The code uses “t” to set tv->tv_sec, and uses milliseconds in “st” to assign tv->tv_usec; at this time, the value is wrong, x + 1 seconds 0 milliseconds, and it will read out x seconds 0 milliseconds incorrectly.

**Review by sangshuduo — APPROVED** [review]
LGTM

**Comment by sangshuduo** [comment]
> > Seems TDengine 3.0/main still use same logic of implementation. interested why taos-tools need to change.
> 
> In such a scenario, an error will occur. At the moment of x seconds and 999 milliseconds, the value of the variable ”t“ is obtained through toolsGetTimestampSec, and the value of the variable ”st” is obtained through the GetLocalTime function at the moment of x + 1 seconds and 0 milliseconds;
> 
> The code uses “t” to set tv->tv_sec, and uses milliseconds in “st” to assign tv->tv_usec; at this time, the value is wrong, x + 1 seconds 0 milliseconds, and it will read out x seconds 0 milliseconds incorrectly.

Any plan to fix similar issue of TDengine?

**Pull request merged**
